### ISSUE TITLE
Images with Emacs pre installed

### ISSUE THREAD

**Issue by larsbrinkhoff** [larsbrinkhoff/emacs-history#6]
Maybe it would be nice to have a select few versions of Emacs pre installed on ready to run disk images.

**Comment by larsbrinkhoff** [comment]
@techfury90 admitted to having GNU Emacs 18.51 running on X11R1 on his Sun 3/60.  Perhaps this feat could be reproduced using a software emulator?

**Comment by noahfriedman** [comment]
I've built (and run) 16.56 successfully in a 4.3bsd-vax simh instance.  Really gives you that mid 80s experience.  I think it would make more sense to distribute it as a tar image than an entire virtual machine, though.

**Comment by AkihiroSuda** [comment]
> I think it would make more sense to distribute it as a tar image than an entire virtual machine, though.

Maybe as a Docker image like this? https://github.com/jguillaumes/dockersimh

**Comment by larsbrinkhoff** [comment]
Thanks, that is great news @noahfriedman.

I'd be interested in repeating your feat.  I did try with 4.1BSD some time ago, but it lacked some things 16.56 needs.  Did you use vanilla 4.3BSD or some other variant?  Installed from tapes or some other way?  Any quirks building Emacs?

Some kind of ready built image is nice.  But I usually prefer a reproducible build kind of thing.  Detailed build instructions are great, and an automated script is even better (see http://github.com/PDP-10/its).

**Comment by larsbrinkhoff** [comment]
Another interesting thing would be to try to resurrect Emacs 13.8.  The files seem to have some VMS damage done to them.

**Comment by noahfriedman** [comment]
I made an image based on 4.3BSD-Quasijarus0c probably close to 10 years ago so I don't remember the build details now (I wish I'd been more diligent about keeping notes back then).  But I found someone else's instructions here: http://gunkies.org/wiki/Installing_4.3_BSD_Quasijarus_on_SIMH so that might something to verify/correct as a first pass at reconstructing disks.

My images, and some additional packages including my premade build of emacs 16.56 that goes into /usr/local, are in ftp://ftp.splode.com/pub/users/friedman/vm/simh-vax-bsd43-quas0c/   (I really should make that http-accessible...)

**Comment by noahfriedman** [comment]
Looks like I have a build of emacs 18.59 and 19.34 in the packages/lude.vax-bsd43.2010-10-25.tar.xz file as well, and a few other GNU packages of a vintage that were probably painless to build.

**Comment by noahfriedman** [comment]
I think those installation instructions may actually be the ones I originally used; I made a note in my downloads where I got the tapes and supplemental packages (for things like gcc) from, and it points back to the sourceforge repo maintained by that same person, on http://sourceforge.net/projects/bsd42/

**Comment by noahfriedman** [comment]
> Another interesting thing would be to try to resurrect Emacs 13.8. The files seem to have some VMS damage done to them.

Yeah, I found those and tried to clean it up.  Some of the files were rcs files, which means they definitely didn't come from rms since he didn't start using version control until well into v19 development.

I should upload the results.  I haven't tried to build it yet though.

**Comment by larsbrinkhoff** [comment]
I think it would be interesting to make a SIMH disk image with a suitable BSD and these versions ready to run:
- Montgomery Emacs
- Gosling Emacs
- GNU Emacs 13, 16, 17, maybe 18

**Comment by larsbrinkhoff** [comment]
It's a start:  
https://github.com/larsbrinkhoff/prebuilt-emulator-images-with-interesting-software-installed

**Comment by larsbrinkhoff** [comment]
Wanted: A Sun workstation emulator that is not painful to run on some Linux distribution.

**Comment by noahfriedman** [comment]
I've been using tme (The Machine Emulator), but sans networking since it depends on BPF.  Linux has a comparable but incompatible interface.  I wish it just used TUN/TAP.

**Comment by larsbrinkhoff** [comment]
> I've been using tme (The Machine Emulator)

I started hacking it to get it to run, also gutting the networking.
But I didn't finish.  Could you post your modifications somewhere?
Arguably "someone" should take maintainership and collect the patches
in one place.
