### ISSUE TITLE
Possible source of Emacs 13.8.15

### ISSUE THREAD

**Issue by neozeed** [larsbrinkhoff/emacs-history#8]
https://www.digiater.nl/openvms/decus/zips_unix_attributes/vax85b.zip

Files are all timestamped from June 19 1985.

vax85b/gnuemax

although it doesn't seem to extract all that cleanly (some VAX version of ZIP expected?)

I haven't tried to build it though.

**Comment by johnsonjh** [comment]
@neozeed

Hi neozeed, ltns, last I talked to seems to be back in [2016](https://virtuallyfun.com/wordpress/2016/09/18/main-quasijarus-site-is-down/#comment-172518)...

Coincidentally, I also ran into this same old Emacs source code looking through old DECUS archives, but didn't look further at it or mention it to Lars ... I was looking for a specific VMS version of Emacs written in BLISS (pretty sure it was by DEC's Barry Scott) - haven't found it yet.

I just looked again at the files. The issue isn't the ZIP, really, but, most likely, that it was created using GNVZIP. This is actually working as intended. These files are not ASCII, in fact, but, instead, are raw dumps of the VMS data. If you would extract this archive on a VMS system, it would have all the VMS attributes, etc. Also, these files don't appear to have been saved as RMS Stream_LF format, so the odd nonsense at regular intervals and end of files are likely the RMS record separators.

I'll look at either extracting this on a VMS system, then converting all the files to Stream_LF format and recreating the archive with InfoZip, or writing a quick hack to convert the files on UNIX. 

For a rather sad old discussion on this, look [over here](https://groups.google.com/u/1/g/comp.os.vms/c/3GtONC0OGUQ)...

**Comment by neozeed** [comment]
I’m basically useless on VMS… although I’d start by setting up a HEC net/DECnet node and using that to transfer files in and out, as network access has to be better than mucking about with tapes.

I have a version of 4.7 all setup from Italy when I helped them backport some idle code….

I think I have people on my discord that are VMS’ers so I can ask them.

I probably spend too much time there  instead of blogging but here is the thing

Discord channel added by popular request | Fun with virtualization (virtuallyfun.com)<https://virtuallyfun.com/wordpress/2020/05/20/discord-channel-added-by-popular-request/>

If the bridge is up it’s #virtuallyfun on freenode

**Comment by larsbrinkhoff** [comment]
Sorry, I seem to have missed this discussion and only saw it just now.

I think the digiater.nl files are the same here under decuslib.com/decus/vax85b/gnuemax.

It would be interesting to do the VMS unmangling to extract useful source files.  Maybe it could then be  built under 4.2BSD or thereabouts.

**Comment by johnsonjh** [comment]
I'll unmangle them this weekend.

**Comment by neozeed** [comment]
Wow it really is 1985!

/* GNU Emacs site configuration file.
   Copyright (C) 1985 Richard M. Stallman.

This file is part of GNU Emacs.

GNU Emacs is distributed in the hope that it will be useful,
but without any warranty.  No author or distributor
________________________________

**Comment by larsbrinkhoff** [comment]
@neozeed I think this is proof it's the real deal: 
https://github.com/larsbrinkhoff/emacs-history/blob/sources/decuslib.com/decus/vax85b/gnuemax/emacs/src/display.c#L25-L67

**Comment by larsbrinkhoff** [comment]
@johnsonjh, no pressure or anything but I'm very interested in seeing the unmangled files.  And ultimately try to build and run it.  How about a SIMH disk image with ~4.2BSD and a bunch of GNU Emacs versions, say 13-17, installed?  CC @noahfriedman FYI

**Comment by johnsonjh** [comment]
@larsbrinkhoff Sorry, totally slipped my mind. It's just a matter of finding the old tools, which I believe I have handy.

**Comment by larsbrinkhoff** [comment]
@johnsonjh I SAID NO PRESSURE!!  But I didn't mean it.

**Comment by dodona2** [comment]
why a vms release in '85? 

As far as I remember RMS&Company owned ad worked on a 'scientific unix workstation'. vms was totally unrelated to the its/twenex experienced RMS. Furthermore the goslin code was UNIX code!

**Comment by larsbrinkhoff** [comment]
I think RMS worked on 4.2BSD on VAX, and later also Sun workstations.

The VMS port was most likely done by other people.  `etc/distrib.dat` says "Efforts are being made to port it to otherUnix versions, and to VMS."

**Comment by larsbrinkhoff** [comment]
@TheFausap sent me a finished installation of Ultrix-32 4.0.  With some minor edits I was able to compile and run Gosling Emacs (emacs.tap in this repository) and GNU Emacs 16.

**Comment by larsbrinkhoff** [comment]
I'm trying my own quick'n'dirty conversion of Emacs 13.  First demangling file names removing 3v and .dat.  Second, removing NUL characters in text files.  Now most files will compile.   There's some more mangling, presumably due to limitations of VMS file names.  They are truncated, lose a dash character, upper case goes lower, etc.

**Comment by larsbrinkhoff** [comment]
There's some damage to file contents too.  For example, `simple.elc` starts with a `Y` which shouldn't be there.

**Comment by larsbrinkhoff** [comment]
It was a year ago, but as I recall I managed to clean up GNU Emacs 13 and build and run it on Ultrix-32.
